$pdf_mode = 1;
$pdflatex = 'xelatex -interaction=nonstopmode -synctex=1 -out-directory=build %O %S';

$out_dir = 'build';
$aux_dir = 'build';

$pdf_dir = '.';
$clean_ext = "acn acr alg bbl bcf blg glg glo gls ist run.xml synctex.gz";
